CREATE TEMP TRIGGER correction_guard_source_insert
BEFORE INSERT ON source_object
WHEN NEW.object_ref <> 'object-c'
  OR NEW.object_kind <> 'pair'
  OR NEW.logical_value <> 'value-c'
BEGIN
    SELECT RAISE(ABORT, 'LICIUM_BC02_CORRECTION_WRITE_FORBIDDEN');
END;

CREATE TEMP TRIGGER correction_guard_source_update
BEFORE UPDATE ON source_object
BEGIN
    SELECT RAISE(ABORT, 'LICIUM_BC02_CORRECTION_WRITE_FORBIDDEN');
END;

CREATE TEMP TRIGGER correction_guard_source_delete
BEFORE DELETE ON source_object
BEGIN
    SELECT RAISE(ABORT, 'LICIUM_BC02_CORRECTION_WRITE_FORBIDDEN');
END;

CREATE TEMP TRIGGER correction_guard_request_insert
BEFORE INSERT ON root_request
BEGIN
    SELECT RAISE(ABORT, 'LICIUM_BC02_CORRECTION_WRITE_FORBIDDEN');
END;

CREATE TEMP TRIGGER correction_guard_request_update
BEFORE UPDATE ON root_request
BEGIN
    SELECT RAISE(ABORT, 'LICIUM_BC02_CORRECTION_WRITE_FORBIDDEN');
END;

CREATE TEMP TRIGGER correction_guard_request_delete
BEFORE DELETE ON root_request
BEGIN
    SELECT RAISE(ABORT, 'LICIUM_BC02_CORRECTION_WRITE_FORBIDDEN');
END;

CREATE TEMP TRIGGER correction_guard_required_insert
BEFORE INSERT ON root_required_member
BEGIN
    SELECT RAISE(ABORT, 'LICIUM_BC02_CORRECTION_WRITE_FORBIDDEN');
END;

CREATE TEMP TRIGGER correction_guard_required_update
BEFORE UPDATE ON root_required_member
BEGIN
    SELECT RAISE(ABORT, 'LICIUM_BC02_CORRECTION_WRITE_FORBIDDEN');
END;

CREATE TEMP TRIGGER correction_guard_required_delete
BEFORE DELETE ON root_required_member
BEGIN
    SELECT RAISE(ABORT, 'LICIUM_BC02_CORRECTION_WRITE_FORBIDDEN');
END;

CREATE TEMP TRIGGER correction_guard_root_insert
BEFORE INSERT ON root
BEGIN
    SELECT RAISE(ABORT, 'LICIUM_BC02_CORRECTION_WRITE_FORBIDDEN');
END;

CREATE TEMP TRIGGER correction_guard_root_update
BEFORE UPDATE ON root
BEGIN
    SELECT RAISE(ABORT, 'LICIUM_BC02_CORRECTION_WRITE_FORBIDDEN');
END;

CREATE TEMP TRIGGER correction_guard_root_delete
BEFORE DELETE ON root
BEGIN
    SELECT RAISE(ABORT, 'LICIUM_BC02_CORRECTION_WRITE_FORBIDDEN');
END;

CREATE TEMP TRIGGER correction_guard_member_insert
BEFORE INSERT ON root_member
BEGIN
    SELECT RAISE(ABORT, 'LICIUM_BC02_CORRECTION_WRITE_FORBIDDEN');
END;

CREATE TEMP TRIGGER correction_guard_member_update
BEFORE UPDATE ON root_member
BEGIN
    SELECT RAISE(ABORT, 'LICIUM_BC02_CORRECTION_WRITE_FORBIDDEN');
END;

CREATE TEMP TRIGGER correction_guard_member_delete
BEFORE DELETE ON root_member
BEGIN
    SELECT RAISE(ABORT, 'LICIUM_BC02_CORRECTION_WRITE_FORBIDDEN');
END;

CREATE TEMP TRIGGER correction_guard_ancestry_insert
BEFORE INSERT ON root_ancestry
BEGIN
    SELECT RAISE(ABORT, 'LICIUM_BC02_CORRECTION_WRITE_FORBIDDEN');
END;

CREATE TEMP TRIGGER correction_guard_ancestry_update
BEFORE UPDATE ON root_ancestry
BEGIN
    SELECT RAISE(ABORT, 'LICIUM_BC02_CORRECTION_WRITE_FORBIDDEN');
END;

CREATE TEMP TRIGGER correction_guard_ancestry_delete
BEFORE DELETE ON root_ancestry
BEGIN
    SELECT RAISE(ABORT, 'LICIUM_BC02_CORRECTION_WRITE_FORBIDDEN');
END;
